### ISSUE TITLE
chore: starknet.js integrate new tooling

### ISSUE THREAD

**Issue by b0xtch** [Psychedelic/terabethia#35]
Starknet goerli has introduced fees into their network. Starknet.js deprecated a few functions that we use on AWS to send calls to the goerli testnet.

- [x] upgrade to use the new version of starknet.js
- [x] [core/aws/src/libs/starknet/index.ts](https://github.com/Psychedelic/terabethia/commit/7e02fbe245c8093ec64fa065d76882fa9e042f5d#diff-58c0d6146746e10fee441cd1793cab9012f1c78a594f7a6fae149aa8114b63bb) need to integrate the new function `callContract`. 
- [x] refer to [starknet API account](https://www.starknetjs.com/docs/API/account) to use the signer and the account to integrate the fee payments

**Comment by fcavazzoli** [comment]
#37
